# permissions for end users to view requests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: request-viewer-role
rules:
- apiGroups:
  - delivery.order.com
  resources:
  - requests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.order.com
  resources:
  - requests/status
  verbs:
  - get
