kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: prow
  name: "branchprotector"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: "branchprotector"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "branchprotector"
subjects:
  - kind: ServiceAccount
    name: "branchprotector"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-pods
  name: "branchprotector"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "branchprotector"
subjects:
  - kind: ServiceAccount
    name: "branchprotector"
    namespace: prow
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: prow
  name: branchprotector
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: branchprotector
    spec:
      template:
        spec:
          serviceAccountName: branchprotector
          containers:
            - name: branchprotector
              image: gcr.io/k8s-prow/branchprotector:v20220414-949f7bddd3
              imagePullPolicy: Always
              args:
                - --config-path=/etc/config/config.yaml
                - --confirm
                - --github-endpoint=https://api.github.com
                - --github-app-id=$(GITHUB_APP_ID)
                - --github-app-private-key-path=/etc/github/cert
              env:
                - name: GITHUB_APP_ID
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: appid
              volumeMounts:
                - name: github-token
                  mountPath: /etc/github
                  readOnly: true
                - name: config
                  mountPath: /etc/config
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: github-token
              secret:
                secretName: github-token
            - name: config
              configMap:
                name: config
