# These are just sample secrets needed for prow, you need to generate the secrets by
# following the instructions in test-infra/config/README.md on how to create the secrets.
apiVersion: v1
kind: Secret
metadata:
  name: github-token
stringData:
  cert: <<insert-downloaded-cert-here>>
  appid: <<insert-the-app-id-here>>
---
apiVersion: v1
kind: Secret
metadata:
  name: hmac-token
stringData:
  # Generate via `openssl rand -hex 20`. This is the secret used in the GitHub webhook configuration
  hmac: << insert-hmac-token-here >>
