apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: local
nodes:
  - role: control-plane
    kubeadmConfigPatches: # this patch in the control-plane since kubeadm runs here
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
